//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayewoPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminSideBar
    {
        public int SideBarId { get; set; }
        public string SideBarTitle { get; set; }
        public string CoverImageUrl { get; set; }
        public byte[] ProfileImageUrl { get; set; }
    }
}
