//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayewoPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Future
    {
        public int FutureId { get; set; }
        public string Header { get; set; }
        public string NameSurname { get; set; }
        public string Title { get; set; }
    }
}
